version: '3.7'
services:
    tn_warehouse:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=francoscagnetti
          - POSTGRES_PASSWORD=postgresadmin
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
